services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file:
      - /defaults.env
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: false
      WATCHTOWER_SCHEDULE: 0 0 2 * * *
      WATCHTOWER_NOTIFICATION_REPORT: false
    networks:
      - gotify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
networks:
  gotify:
    external: true
